spring:
  datasource:
    url: jdbc:mysql://[IP주소]:[port번호]/plantgo
    username: 'plantgo'
    password: '[비밀번호]'

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: 
            client-secret: 
            clientAuthenticationMethod: post
            redirect-uri: "http://j7a703.p.ssafy.io:8080/login/oauth2/code/NAVER"
            authorization-grant-type: authorization_code
            scope:
              - nickname
              - email
              - profile_image
            client-name : Naver
          google:
            clientId: 
            clientSecret: 
            redirect-uri: "http://j7a703.p.ssafy.io:8080/login/oauth2/code/GOOGLE"
            scope:
              - email
              - profile
          kakao:
            clientId: 
            clientSecret: 
            clientAuthenticationMethod: post
            authorizationGrantType: authorization_code
            redirectUri: "http://j7a703.p.ssafy.io:8080/login/oauth2/code/KAKAO"
            scope:
              - profile_nickname
              - profile_image
              - account_email
            clientName: Kakao
        # Provider 설정
        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id

# cors 설정
#cors:
#  allowed-origins: 'https://j7a703.p.ssafy.io'
#  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
#  allowed-headers: '*'
#  max-age: 3600

# jwt secret key 설정
jwt.secret: ''

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 
    tokenExpiry: 
    refreshTokenExpiry: 
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth/redirect


cloud:
  aws:
    credentials:
      accessKey: 
      secretKey: 
    s3:
      bucket: 
      dir: /
    region:
      static: ap-northeast-2
    stack:
      auto: false

